#!/bin/bash

function error {
    echo "$1" >&2
}

configfile=/etc/network-monitor-alarm.conf

while IFS='= ' read lhs rhs
do
    #echo "<${lsh}> <${rhs}>"
    if [[ ! $lhs =~ ^# && -n $lhs ]]; then
        declare $lhs="$rhs"
        #echo "${lhs} = ${!lhs}"
    fi
done < $configfile

if [[ -z $alarm_network || -z $alarm_internet || -z $test_domain ]]; then
    error "Error: configuration file not set"
    exit 1
fi

# test if network exists (ping gateway)
ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null 2>&1
gateway=$?

if [[ $gateway == 0 ]]; then
    # test if internet exists (ping
    ping -q -w 1 -c 1 "$test_domain" > /dev/null 2>&1
    internet=$?

    if [[ $internet == 0 ]]; then
        # do nothing
        echo "Pass: internet active" > /dev/null
    else
        error "Fail: No internet"
        eval "$alarm_internet"
    fi
else
    error "Fail: No network found"
    eval "$alarm_network"
fi
exit 0
